### ISSUE TITLE
Need Documentation for Using MedplumClient with React Native.

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [medplum/medplum#1657]
Hi,

Is there any page where can I find the code/ REST API for patient login in React Native App?

**Comment by codyebberson** [comment]
Hi @nilaybrahmbhatt 

I just pushed this example app: https://github.com/medplum/medplum-react-native-example

It is simple, and has important limitations.  The most significant limitation is that it does not support all of the different forms of Medplum authentication (multiple profiles, SMART scopes, federated identities, external auth providers, etc).

I hope it helps.  Please let us know if you have any questions or any feedback.

**Comment by nilaybrahmbhatt** [comment]
hi @codyebberson ,
I update the @medplum/core to 2.0.7 && used your code in my app

`medplum.startLogin({ email: formData.email, password: formData.password }).then((res)=>{
            console.log(res);
});
`

but I got error 
`Property 'crypto' doesn't exist`

<img width="1071" alt="Screenshot 2023-03-20 at 5 30 27 PM" src="https://user-images.githubusercontent.com/6310631/226333550-915a5a22-1062-4a6d-b0b3-b51a8f8583d1.png">

My React Native Application is build using react-native CLI method not expo.

**Comment by Mindbowser** [comment]
Any luck here? We are also facing same issue. @nilaybrahmbhatt have you solved it?

**Comment by ThatOneBro** [comment]
Hey @Mindbowser!

Try checking out https://github.com/medplum/medplum/tree/main/packages/expo-polyfills, this package should likely fix most of the issues you may be running into. You can use it whether you are using Expo or not

 Let me know if you need any guidance on it or if the package README is not clear

**Comment by anujapisemb** [comment]
Hi @ThatOneBro ,
I checked installing package you've mentioned but still getting same error. Additionally after adding configuration mentioned in README file introduced some other error as below when we instantiate client by passing storage:
Error: Cannot find native module 'ExpoSecureStore', js engine: hermes

Also sharing code snippet where its breaking
![Screenshot 2024-02-01 at 6 35 16 PM](https://github.com/medplum/medplum/assets/92784411/5fef7763-c405-4db7-830b-9e7c87408616)
